title: "BLFC: A Musical Tail"
event_dates: May 10-13th, 2018
event_location: Reno, Nevada




description: Furry / Anthropomorphic Convention in Reno, Nevada.
keywords: Furry, Anthropomorphic, Anthro, Convention, Gathering, Event, Con, Animals, BLFC, Reno, Nevada, 2018, PawFur, Biggest Little Furry Convention

permalink: pretty
theme: minima
markdown: kramdown
kramdown: 
  parse_block_html: true


social:
  - slug: facebook
    name: Facebook
    url: "https://www.facebook.com/BiggestLittleFurryConvention"
  - slug: twitter
    name: Twitter
    url: "https://twitter.com/BiggestLittleFC"
  - slug: tumblr
    name: Tumblr
    url: "http://biggestlittlefc.tumblr.com/"
  - slug: paw
    name: FurAffinity
    url: "http://www.furaffinity.net/user/biggestlittlefurcon"
  - slug: youtube
    name: YouTube
    url: "https://www.youtube.com/c/BiggestlittlefurconOrg"
  - slug: google-plus
    name: Google Plus
    url: "https://plus.google.com/106338588646241282653/posts"
  - slug: telegram
    name: Telegram
    url: "https://telegram.me/biggestlittlefc"
  - slug: instagram
    name: Instagram
    url: "https://www.instagram.com/biggestlittlefurcon/"